name: "Hello World"
description: "Greet someone and record the time"
inputs:
  username:
    description: "Your Github username"
    required: true
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node12"
  main: "index.js"
