name: "Wakatime README"
description: "Add your wakatime datas on your REAME.md powered by JavaScript."

inputs:
  GH_TOKEN:
    description: "Your Github token"
    required: true
  WT_TOKEN:
    description: "Your Wakatime token"
    required: true
  USERNAME:
    description: "Your Github username"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
